<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class MTembusan extends CI_Model
{

    public $table = 'tembusan';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }



    // get total rows
    function total_rows($q = NULL)
    {
        $this->db->select('s.id');
        $this->db->from('surat s');
        $this->db->join('tembusan t', 't.id_surat = s.id');
        $this->db->join('users u', 'u.id = t.kepada');
        $this->db->group_by('s.id');
        $this->db->where('t.kepada', $this->session->userdata('user_id'));
        $this->db->where("(s.perihal LIKE '%" . $q . "%' OR nomor_surat LIKE '%" . $q . "%' )");
        return $this->db->count_all_results();
    }

    function kepada_tembusan($id_surat)
    {
        $this->db->select('t.*, u.first_name, u.last_name, u.jabatan');
        $this->db->from('tembusan t');
        $this->db->join('users u', 'u.id = t.kepada', 'left');
        // $this->db->join('surat_lampiran sl', 'sl.id_tujuan = t.id');
        $this->db->where('t.id_surat', $id_surat);
        // $this->db->where('t.isi', NULL);
        return $this->db->get()->result();
        //$this->db->get()->result(); echo $this->db->last_query(); exit;
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL)
    {
        $this->db->select('s.*,t.kepada, t.dari,(SELECT first_name from users where id = t.dari) nama_depan, (SELECT last_name from users where id = t.dari) nama_belakang');
        $this->db->from('surat s');
        $this->db->join('tembusan te', 'te.id_surat = s.id');
        $this->db->join('tujuan t', 't.id_surat = s.id');
        $this->db->join('users u', 'u.id = t.kepada');
        $this->db->where('te.kepada', $this->session->userdata('user_id'));
        $this->db->where("(s.perihal LIKE '%" . $q . "%' OR nomor_surat LIKE '%" . $q . "%' )");
        $this->db->group_by('s.id');
        $this->db->order_by($this->id, $this->order);
        $this->db->limit($limit, $start);
        return $this->db->get()->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

    // delete bulkdata
    function deletebulk()
    {
        $data = $this->input->post('msg_', TRUE);
        $arr_id = explode(",", $data);
        $this->db->where_in($this->id, $arr_id);
        return $this->db->delete($this->table);
    }
}

/* End of file MTembusan.php */
/* Location: ./application/models/MTembusan.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-09-02 08:33:40 */
/* http://harviacode.com */