<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Permission_model extends CI_Model
{

    public $table = 'permission';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    function get_all_by_id_groups($id_group)
    {
        /*
        SELECT u.id as id_user, u.first_name, p.id_groups as dari, ug.group_id as kepada
        FROM users u
        LEFT JOIN users_groups ug on ug.user_id = u.id
        JOIN permission p on p.id_groups_to = ug.group_id
        WHERE p.id_groups = 17
        GROUP BY ug.group_id
        */
        $this->db->select('u.id as id_user, u.first_name, p.id_groups as dari, ug.group_id as kepada');
        $this->db->from('users u');
        $this->db->join('users_groups ug', 'ug.user_id = u.id', 'left');
        $this->db->join('permission p', 'p.id_groups_to = ug.group_id');
        $this->db->where('p.id_groups', $id_group);
        $this->db->group_by('ug.group_id');

        return $this->db->get()->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL)
    {
        $this->db->like('id', $q);
        $this->db->or_like('id_groups', $q);
        $this->db->or_like('id_groups_to', $q);
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    // function get_limit_data($limit, $start = 0, $q = NULL)
    // {

    //     $this->db->order_by($this->id, $this->order);
    //     $this->db->like('id', $q);
    //     $this->db->or_like('id_groups', $q);
    //     $this->db->or_like('id_groups_to', $q);
    //     $this->db->limit($limit, $start);
    //     return $this->db->get($this->table)->result();
    // }

    function get_limit_data($limit, $start = 0, $q = NULL)
    {
        //join permission dengan groups
        $this->db->select('b.*, k.name,(SELECT name from groups where id = b.id_groups_to) name2');
        $this->db->from('permission b');
        $this->db->join('groups k', 'k.id=b.id_groups');

        $this->db->order_by('b.id', $this->order);
        $this->db->like('b.id', $q);
        $this->db->or_like('k.name', $q);
        // $this->db->or_like('k.harga', $q);
        // $this->db->or_like('b.kode_menu', $q);
        $this->db->limit($limit, $start);
        return $this->db->get()->result();
    }
    function get_limit_data2()
    {
        //join permission dengan groups
        $this->db->select('b.id_groups_to, k.name');
        $this->db->from('permission b');
        $this->db->join('groups k', 'k.id=b.id_groups_to');

        return $this->db->get()->result();
    }



    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

    // delete bulkdata
    function deletebulk()
    {
        $data = $this->input->post('msg_', TRUE);
        $arr_id = explode(",", $data);
        $this->db->where_in($this->id, $arr_id);
        return $this->db->delete($this->table);
    }

    function getUserGroups($user_id)
    {
        $query = "SELECT `users_groups`.*,`groups`.`name`
    FROM `users_groups` JOIN `groups`
    ON `users_groups`.`group_id` = `groups`.`id`
    WHERE user_id=$user_id
    ";

        return $this->db->query($query)->row_array();
    }


    function get_permision($x, $y)
    {
        $this->db->select('id');
        $this->db->from('permission');
        $this->db->where('id_groups', $x);
        $this->db->where('id_groups_to', $y);
        return $this->db->get()->row_array();
    }
}

/* End of file Permission_model.php */
/* Location: ./application/models/Permission_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-09-02 06:19:24 */
/* http://harviacode.com */